### ISSUE TITLE
Add a option to teleport to spawn on join

### ISSUE THREAD

**Issue by mikeygio10** [minijaham/SpawnCommand#1]
Add a option to teleport to spawn on join

**Comment by minijaham** [comment]
Alright! I'll work on that

**Comment by minijaham** [comment]
> Add a option to teleport to spawn on join

https://poggit.pmmp.io/p/AlwaysSpawn/2.2.4

There's already a plugin for it. You can go check it out :)

**Comment by minijaham** [comment]
> Add a option to teleport to spawn on join

Check out https://github.com/minijaham/ForceSpawn

**Comment by minijaham** [comment]
I've made a little edit. Now you can toggle on/off the force spawn on join in config.yml. Install the latest version and try.
